return {
    Group = require(script.Group),
    Frame = require(script.Frame),
    TextLabel = require(script.TextLabel),
    ImageLabel = require(script.ImageLabel),
    ImageButton = require(script.ImageButton),
    AspectRatio = require(script.AspectRatio),
    TextBox = require(script.TextBox),
    ScrollingFrame = require(script.ScrollingFrame),
    CanvasGroup = require(script.CanvasGroup)
}